FROM registry.fedoraproject.org/fedora:28

ARG VERSION

ENV VCS_URL="https://github.com/Nitrate/Nitrate"

LABEL version="$VERSION"                                                   \
      maintainer="Chenxiong Qi <qcxhome@gmail.com>"                        \
      description="Run Nitrate from a Python virtual environment behind \
httpd. Authentication is not special. Common username and password \
authentication is used by default. A default superuser is created, both \
username and password are 'admin'."                                        \
      io.github.nitrate.url="https://nitrate.readthedocs.io/"              \
      io.github.nitrate.vcs-url="${VCS_URL}"                               \
      io.github.nitrate.issues-url="${VCS_URL}/issues/"

# install virtualenv and libraries needed to build the python dependencies
RUN dnf update -y                                                       && \
    dnf install -y gcc python3-devel graphviz-devel                        \
        httpd mariadb python3-mod_wsgi                                  && \
    dnf clean all

# Download released tarball and extract to /code
# Note that, archive tarball created by GitHub has prefix Nitrate-${version}.
# For convenience, move all files under that prefix to /code.
RUN mkdir /code                                                         && \
    cd /tmp                                                             && \
    curl -L -O ${VCS_URL}/archive/v${VERSION}.tar.gz                    && \
    tar xf /tmp/v${VERSION}.tar.gz --directory /code                    && \
    mv /code/Nitrate-${VERSION}/* /code                                 && \
    rm /tmp/v${VERSION}.tar.gz

# Create a virtualenv for the application dependencies
# Using --system-site-packages b/c Apache configuration
# expects the tcms directory to be there!
RUN python3 -m venv --system-site-packages /prodenv                     && \
    sed -i -e 's/from common import/from tcms.settings.common import/'     \
        /code/src/tcms/settings/product.py                              && \
    sed -i -e 's/MIDDLEWARE_CLASSES/MIDDLEWARE/'                           \
        /code/src/tcms/settings/product.py                              && \
    /prodenv/bin/pip install --no-cache-dir /code

COPY ./contrib/conf/nitrate-httpd.conf /etc/httpd/conf.d/
COPY ./contrib/conf/wsgi-venv.conf /etc/httpd/conf.d/

# Modify configuration files
RUN sed -i -e 's/^#\(LoadModule mpm_prefork_module .\+\.so\)$/\1/'         \
        /etc/httpd/conf.modules.d/00-mpm.conf                           && \
    sed -i -e 's/^\(LoadModule mpm_event_module .\+\.so\)$/#\1/'           \
        /etc/httpd/conf.modules.d/00-mpm.conf

# Configure directory to hold uploaded files
RUN mkdir -p /var/nitrate/uploads                                       && \
    chown apache:apache /var/nitrate/uploads                            && \
    mkdir -p /usr/share/nitrate/static                                  && \
    /prodenv/bin/python /code/manage.py collectstatic                      \
        --settings=tcms.settings.product --noinput

# All the things are installed already. No need to keep source code inside.
RUN rm -rf /code

EXPOSE 80

VOLUME ["/var/www", "/var/log/httpd"]

CMD ["httpd", "-D", "FOREGROUND"]
