const jsdoc = require('eslint-plugin-jsdoc');

module.exports = [
  jsdoc.configs['flat/recommended'],
  {
    files: ['**/*.js'],
    plugins: {
      jsdoc: jsdoc
    },
    languageOptions: {
      ecmaVersion: 2018,
      sourceType: 'script',
      globals: {
        // Browser environment
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        DOMParser: 'readonly',
        XMLHttpRequest: 'readonly',
        HTMLElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',

        // ES6 globals
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',

        // jQuery
        $: 'readonly',
        jQuery: 'readonly',

        // QUnit
        QUnit: 'readonly',
        test: 'readonly',
        asyncTest: 'readonly',
        expect: 'readonly',
        module: 'readonly',
        ok: 'readonly',
        equal: 'readonly',
        notEqual: 'readonly',
        deepEqual: 'readonly',
        notDeepEqual: 'readonly',
        strictEqual: 'readonly',
        notStrictEqual: 'readonly',
        throws: 'readonly',
        start: 'readonly',
        stop: 'readonly',

        // Vendors
        Handlebars: 'readonly',
        SelectBox: 'readonly',
        SelectFilter: 'readonly',
        TableDnD: 'readonly',

        // Nitrate globals
        jQ: 'readonly',
        Nitrate: 'writable',

        SORT_KEY_MIN: 'readonly',
        SORT_KEY_MAX: 'readonly',
        isSortKeyInAllowedRange: 'readonly',

        getBuildsByProductId: 'readonly',
        getCategoriesByProductId: 'readonly',
        getComponentsByProductId: 'readonly',
        getVersionsByProductId: 'readonly',
        registerProductAssociatedObjectUpdaters: 'readonly',

        getRequest: 'readonly',
        patchRequest: 'readonly',
        postHTMLRequest: 'readonly',
        postRequest: 'readonly',
        postToURL: 'readonly',
        sendHTMLRequest: 'readonly',

        removeComment: 'readonly',
        submitComment: 'readonly',
        updateCommentsCount: 'readonly',

        CaseTagsView: 'readonly',
        PlanTagsView: 'readonly',
        RunTagsView: 'readonly',

        blinddownAllCases: 'readonly',
        blindupAllCases: 'readonly',
        clearDialog: 'readonly',
        confirmDialog: 'readonly',
        constructAjaxLoading: 'readonly',
        constructForm: 'readonly',
        defaultMessages: 'readonly',
        emptySelect: 'readonly',
        getDialog: 'readonly',
        getSelectedCaseIDs: 'readonly',
        globalCsrfToken: 'readonly',
        id_to_windowname: 'readonly',
        popupAddAnotherWindow: 'readonly',
        previewPlan: 'readonly',
        renderComponentForm: 'readonly',
        setUpChoices: 'readonly',
        showModal: 'readonly',
        SHORT_STRING_LENGTH: 'readonly',
        splitString: 'readonly',
        updateObject: 'readonly',
        createInputElement: 'readonly',
      }
    },
    rules: {
      // ESLint recommended rules
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-semi': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-new-symbol': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // Custom rules from original config
      'brace-style': ['error', '1tbs', {allowSingleLine: true}],
      'camelcase': ['error', {properties: 'never'}],
      'comma-spacing': 'error',
      'curly': 'error',
      'eqeqeq': 'error',
      'func-call-spacing': 'error',
      'func-style': ['error', 'declaration'],
      'indent': ['error', 2, {SwitchCase: 1}],
      'linebreak-style': ['error', 'unix'],
      'max-len': ['error', {code: 120, ignoreUrls: true}],
      'no-trailing-spaces': 'error',
      'no-unused-vars': ['error', {caughtErrors: 'none', vars: 'local', args: 'none'}],
      'no-var': 'error',
      'object-curly-spacing': 'error',
      'operator-linebreak': ['error', 'after'],
      'quotes': ['error', 'single', {avoidEscape: true}],
      'space-before-function-paren': ['error', {anonymous: 'always', named: 'never', asyncArrow: 'always'}],
      'space-infix-ops': 'error',

      // JSDoc rules - adjust from recommended config
      'jsdoc/require-jsdoc': 'off',
      'jsdoc/tag-lines': 'off',
      'jsdoc/no-defaults': 'off',
      'jsdoc/require-returns': 'off',
      'jsdoc/check-tag-names': 'off'
    }
  }
];
