# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 01:56
from django.db import migrations
import tcms.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_add_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testbuild",
            name="is_active",
            field=tcms.core.models.fields.NitrateBooleanField(db_column="isactive", default=True),
        ),
    ]
