# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 14:17
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0004_set_testenvironmentelement_parent_to_null_if_parent_is_deleted",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testattachment",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
