# Generated by Django 2.2.1 on 2019-05-25 14:54

from django.db import migrations, models
import django.db.models.deletion

# attachment is changed to OneToOneField


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_set_testattachment_submitter_to_null_if_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testattachmentdata",
            name="attachment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.TestAttachment",
            ),
        ),
    ]
