# Generated by Django 3.0.7 on 2020-08-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkcategory",
            name="user",
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
        migrations.DeleteModel(
            name="BookmarkCategory",
        ),
    ]
