# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 15:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuetracker", "0005_adjust_issue_report_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productissuetrackerrelationship",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="The corresponding product name in issue tracker.",
                max_length=50,
                null=True,
            ),
        ),
    ]
