# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 11:58
from django.db import migrations


# This migration could be dropped when squash migrations from scratch.


def forwards(apps, schema_editor):
    IssueTracker = apps.get_model("issuetracker", "IssueTracker")

    bz = IssueTracker.objects.get(name="Bugzilla")
    bz.class_path = "tcms.issuetracker.services.Bugzilla"
    bz.save(update_fields=["class_path"])

    jira = IssueTracker.objects.get(name="JIRA")
    jira.class_path = "tcms.issuetracker.services.JIRA"
    jira.save(update_fields=["class_path"])


class Migration(migrations.Migration):

    dependencies = [
        ("issuetracker", "0009_alter_fields_see_details_inside"),
    ]

    operations = [migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)]
