# Generated by Django 2.1.4 on 2018-12-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issuetracker", "0018_default_groups_uses_issuetracker_perms_instead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="case_run",
            field=models.ForeignKey(
                blank=True,
                help_text="A test case run this issue is associated with optionally.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="testruns.TestCaseRun",
            ),
        ),
    ]
