# Generated by Django 3.1.8 on 2022-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcms_auth", "0002_add_index_to_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivatekey",
            name="activation_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
