# Generated by Django 3.2.12 on 2022-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcms_auth", "0003_enlarge_activation_key_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivatekey",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
