# Generated by Django 3.2.12 on 2022-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testruns", "0008_remove_errata_id_from_testrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcmsenvrunvaluemap",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testruncc",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testruntag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
