# Generated by Django 3.2.14 on 2022-10-23 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0010_set_bigautofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testplantext",
            name="create_date",
            field=models.DateTimeField(db_column="creation_ts", default=django.utils.timezone.now),
        ),
    ]
