# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 06:37
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tcmslogmodel",
            name="field",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="tcmslogmodel",
            name="new_value",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tcmslogmodel",
            name="original_value",
            field=models.TextField(default=""),
        ),
    ]
