name: Linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: |
          sudo apt-get update
          sudo apt-get install -y npm

          uv venv --python 3.13
          source .venv/bin/activate
          uv sync --extra devtools
          tox -e bandit,black,flake8,docs,doc8,isort,templatelint,jslint

  mypy:
    name: Run mypy-${{ matrix.django-version }} checks
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        django-version: [django420]
    steps:
      - run: |
          sudo apt update
          sudo apt-get install gcc python3-dev libkrb5-dev libmariadb-dev libcrypt-dev
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Run mypy
        run: |
          uv venv --python 3.13
          source .venv/bin/activate
          uv sync --extra devtools
          tox -e mypy-${{ matrix.django-version }}
