name: Unit Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  unittests:
    name: "py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.db }}"
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 7
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        django-version: [django420]
        db: [sqlite]
        include:
          - python-version: '3.12'
            django-version: django420
            db: mysql
          - python-version: '3.12'
            django-version: django420
            db: mariadb
          - python-version: '3.12'
            django-version: django420
            db: postgres

    steps:
      - name: Install packages used to setup testenv
        run: |
          sudo apt update
          sudo apt-get install -y jq make gcc python3-dev libkrb5-dev libmariadb-dev libcrypt-dev

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Run the tests
        env:
          TEST_DB_ENGINE: ${{ matrix.db }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          DJANGO_VERSION: ${{ matrix.django-version }}
        run: |
          set -eu
          set -o pipefail

          uv venv --python python3.13
          source .venv/bin/activate
          uv sync --extra devtools

          tox -l

          start_test_db() {
            make start-testdb-${TEST_DB_ENGINE} detach=yes
            trap 'make stop-testdb-${TEST_DB_ENGINE}' EXIT ERR
            make check-testdb-health db_engine=${TEST_DB_ENGINE}
          }

          [ "x$TEST_DB_ENGINE" = "xsqlite" ] || start_test_db
          tox -e py${PYTHON_VERSION/./}-${DJANGO_VERSION}-${TEST_DB_ENGINE}

      - name: Parallel coverage report
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: testenv-py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.db }}
          parallel: true

  coveralls:
    name: Finish Coveralls
    needs: unittests
    runs-on: ubuntu-latest
    steps:
      - name: Finish coverage report
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
